fs:
  image: tianon/true
  volumes:
    - ./src:/home/rstudio
    - ./src/jekyll/:/src
    - ./shr/dynamic:/srv/shiny-server
    - ./shr/static:/usr/share/nginx/html

fs.jekyll:
  image: tianon/true
  volumes:
    - ./src/jekyll/_site:/usr/share/nginx/html:rw

fs.proxy:
    - ./letsencrypt/certs:/etc/nginx/certs:ro
    - ./letsencrypt/conf:/etc/nginx/vhost.d
    - ./letsencrypt/html:/usr/share/nginx/html

ropensci:
  build: eubon-rocker
  environment:
    - ENCRYPT_EMAIL=dina@mail.dina-web.net
    - ENCRYPT_HOST=wrangler.mirroreum.eu
    - VIRTUAL_HOST=wrangler.mirroreum.eu
    - VIRTUAL_PORT=8787
    - USER=rstudio
    - PASSWORD=rstudio
    - ROOT=TRUE
  ports:
    - "8787:8787"
  volumes_from:
    - fs

shiny:
  image: rocker/shiny
  environment:
    - ENCRYPT_EMAIL=dina@mail.dina-web.net
    - ENCRYPT_HOST=dynamic.mirroreum.eu
    - VIRTUAL_HOST=dynamic.mirroeum.eu
  ports:
    - "3737:3737"
  links:
    - ropensci
  volumes_from:
    - fs

nginx:
  image: nginx
  environment:
    - ENCRYPT_EMAIL=dina@mail.dina-web.net
    - ENCRYPT_HOST=static.mirroreum.eu
    - VIRTUAL_HOST=static.mirroreum.eu
  volumes_from:
    - fs

jekyll:
  image: grahamc/jekyll:next
  command: build --incremental -w
  ports:
    - "4000:4000"
  volumes_from:
    - fs

portal:
  image: nginx
  environment:
    - ENCRYPT_EMAIL=dina@mail.dina-web.net
    - ENCRYPT_HOST=mirroreum.eu,portal.mirroreum.eu,www.mirroreum.eu
    - VIRTUAL_HOST=mirroreum.eu,portal.mirroreum.eu,www.mirroreum.eu
  volumes_from:
    - fs.jekyll

proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  volumes_from:
    - fs.proxy

letsencrypt:
  image: jrcs/lestencrypt-nginx-proxy-companion
  volumes_from:
    - fs.proxy
