fs:
  image: tianon/true
  volumes:
    - ./src:/home/rstudio
    - ./shr/dynamic:/srv/shiny-server
    - ./shr/static:/usr/share/nginx/html

ropensci:
  build: eubon-rocker
  environment:
    - VIRTUAL_HOST=wrangler.local
    - VIRTUAL_PORT=8787
    - USER=rstudio
    - PASSWORD=rstudio
    - ROOT=TRUE
  ports:
    - "8787:8787"
  volumes_from:
    - fs

shiny:
  image: rocker/shiny
  environment:
    - VIRTUAL_HOST=dynamic.local
  ports:
    - "3737:3737"
  links:
    - ropensci
  volumes_from:
    - fs

nginx:
  image: nginx
  environment:
    - VIRTUAL_HOST=static.local
  volumes_from:
    - fs

proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  links:
    - shiny
    - ropensci
    - nginx
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
