fs:
  image: tianon/true
  volumes:
    - ./src:/home/rstudio:rw
    - ./src/jekyll/:/srv/jekyll:rw
    - ./shr/dynamic:/srv/shiny-server:rw
    - ./shr/static:/usr/share/nginx/html:rw

fs.jekyll:
  image: tianon/true
  volumes:
    - ./src/jekyll/_site:/usr/share/nginx/html:ro

fs.proxy:
  image: tianon/true
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

ropensci:
  build: eubon-rocker
#  labels: letsencrypt.nocert=true
  environment:
    - VIRTUAL_HOST=wrangler.mirroreum.eu
    - VIRTUAL_PORT=8787
    - USER=rstudio
    - PASSWORD=rstudio
    - ROOT=TRUE
  volumes_from:
    - fs

shiny:
  image: rocker/shiny
#  labels: letsencrypt.nocert=true
  environment:
    - VIRTUAL_HOST=dynamic.mirroeum.eu
  links:
    - ropensci
  volumes_from:
    - fs

nginx:
  image: nginx
#  labels: letsencrypt.nocert=true
  environment:
    - VIRTUAL_HOST=static.mirroreum.eu
  volumes_from:
    - fs

jekyll:
  image: jekyll/jekyll
  command: bundle exec jekyll build --incremental --watch
  volumes_from:
    - fs

portal:
  image: nginx
#  labels: letsencrypt.nocert=true
  environment:
    - VIRTUAL_HOST=portal.mirroreum.eu
  volumes_from:
    - fs.jekyll

proxy:
  image: eforce21/letsencrypt-nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - fs.proxy
