fs:
  image: tianon/true
  volumes:
    - ./src:/home/rstudio:rw
    - ./src/jekyll:/srv/jekyll:rw
    - ./shr/dynamic:/srv/shiny-server:rw
    - ./shr/static:/usr/share/nginx/html:rw

fs.jekyll:
  image: tianon/true
  volumes:
    - ./src/jekyll/_site:/usr/share/nginx/html:ro

fs.proxy:
  image: tianon/true
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

ropensci:
  build: eubon-rocker
  environment:
    - VIRTUAL_HOST=wrangler.local
    - VIRTUAL_PORT=8787
    - USER=rstudio
    - PASSWORD=rstudio
    - ROOT=TRUE
  volumes_from:
    - fs

shiny:
  image: rocker/shiny
  environment:
    - VIRTUAL_HOST=dynamic.mirroeum.eu
  links:
    - ropensci
  volumes_from:
    - fs

nginx:
  image: nginx
  environment:
    - VIRTUAL_HOST=static.mirroreum.eu
  volumes_from:
    - fs

jekyll:
  image: jekyll/jekyll:3.1.3
  command: bundle exec jekyll serve --watch
#  image: grahamc/jekyll:next
#  command: serve --watch
  labels:
    letsencrypt.nocert: "true"
  ports:
    - "4000:4000"
  environment:
    - VIRTUAL_HOST=mirroreum.eu
    - VIRTUAL_PORT=4000
  volumes:
    - ./src/jekyll:/srv/jekyll

portal:
  image: nginx
  environment:
    - VIRTUAL_HOST=portal.mirroreum.eu
  volumes:
    - ./src/jekyll/_site:/usr/share/nginx/html

proxy:
#  image: eforce21/letsencrypt-nginx-proxy
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - fs.proxy
